setting:
  url: https://vk.com/wall-111111111 # Ссылка на стену группу в конце ссылки нужно указать / например https://vk.com/wall-111111111/ и другие параметры
  filter_after: [] # Фильтрация авторов постов (указывать тех авторов которых не нужно парсить)
  ###################################################
  # Формат даты: ДД.ММ.ГГГГ
  # Если нужно парсить посты с 01.08.2025 по 01.04.2025
  # то нужно указать parse_from: 01.08.2025 и parse_until: 01.04.2025
  # Парсинг начинается с даты parse_from и заканчивается parse_until то есть от 01.08.2025 до 01.04.2025
  ###################################################
  parse_from: 01.08.2025 # Дата поста от которой начнется парсинг 
  parse_until: 01.04.2025 # Дата поста до которой парсить